routes/web.php
<?php

use App\Http\Controllers\DosenController;
use App\Http\Controllers\JurusanController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\LogoutController;
use App\Http\Controllers\MahasiswaController;
use App\Http\Controllers\MatakuliahController;
use App\Http\Controllers\PencarianController;
use App\Models\Dosen;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/',[LoginController::class,'index']);

Route::get('/logout',[LoginController::class,'index']);

Route::resource('jurusans',JurusanController::class);

Route::resource('dosens',DosenController::class);

Route::resource('matakuliahs',MatakuliahController::class);

Route::resource('mahasiswas',MahasiswaController::class);

Route::get('/jurusan-dosen/{jurusan_id}',[JurusanController::class,'jurusanDosen'])->name('jurusan-dosen');

Route::get('/jurusan-mahasiswa/{jurusan_id}',[JurusanController::class,'jurusanMahasiswa'])->name('jurusan-mahasiswa');

Route::get('/jurusan-matakuliah/{jurusan_id}',[JurusanController::class,'jurusanMatakuliah'])->name('jurusan-matakuliah');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('/buat-matakuliah/{dosen}',[MatakuliahController::class,'buatMatakuliah'])->name('buat-matakuliah');

Route::get('/mahasiswas/ambil-matakuliah/{mahasiswa}',[MahasiswaController::class,'ambilMatakuliah'])->name('ambil-matakuliah');

Route::post('/mahasiswas/ambil-matakuliah/{mahasiswa}',[MahasiswaController::class,'prosesAmbilMatakuliah'])->name('proses-ambil-matakuliah');

Route::get('/matakuliahs/dafarkan-mahasiswa/{matakuliah}',[MatakuliahController::class,'daftarkanMahasiswa'])->name('daftarkan-mahasiswa');

Route::post('/matakuliahs/dafarkan-mahasiswa/{matakuliah}',[MatakuliahController::class,'prosesDaftarkanMahasiswa'])->name('proses-daftarkan-mahasiswa');

Route::get('/pencarian',[PencarianController::class,'index']);

Route::get('/pencarian/proses',[PencarianController::class,'proses']);

app/Models/Dosen.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Dosen extends Model
{
    use HasFactory;
    protected $fillable = ['nid','nama','jurusan_id'];

    public function matakuliahs(){
        return $this->hasMany('App\Models\Matakuliah');
    }

    public function jurusan(){
        return $this->belongsTo('App\Models\Jurusan');
    }
}

app/Http/Controllers/DosenController.php
<?php

namespace App\Http\Controllers;

use App\Models\Dosen;
use App\Models\Jurusan;
use Illuminate\Http\Request;
use RealRashid\SweetAlert\Facades\Alert;

class DosenController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function __construct()
    {
        $this->middleware('auth')->except(['index','show']);
    }

    public function index()
    {
        $dosens = Dosen::with('jurusan')->orderBy('nama')->paginate(5);
        return view('dosen.index',['dosens' => $dosens]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $jurusans = Jurusan::orderBy('nama')->get();
        return view('dosen.create',compact('jurusans'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validateData = $request->validate(
            [
                'nid' => 'required|alpha_num|size:8|unique:dosens,nid',
                'nama' => 'required',
                'jurusan_id' => 'required|exists:App\Models\Jurusan,id',
            ]
        );
        $dosen = Dosen::create($validateData);
        Alert::success('Berhasil',"Dosen $dosen->nama berhasil ditambahkan");
        return redirect($request->url_asal);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Dosen  $dosen
     * @return \Illuminate\Http\Response
     */
    public function show(Dosen $dosen)
    {
        return view('dosen.show',compact('dosen'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Dosen  $dosen
     * @return \Illuminate\Http\Response
     */
    public function edit(Dosen $dosen)
    {
        $jurusan = Jurusan::orderBy('nama')->get();
        return view('dosen.edit',['jurusans' => $jurusan,'dosen' => $dosen]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Dosen  $dosen
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Dosen $dosen)
    {
        $validateData = $request->validate(
            [
                'nid' => 'required|alpha_num|size:8|unique:dosens,nid,'.$dosen->id,
                'nama' => 'required',
                'jurusan_id' => 'required|exists:App\Models\Jurusan,id'
            ]
        );

        $dosen->update($validateData);

        Alert::success('Berhasil',"Dosen $dosen->nama telah di update");

        return redirect($request->url_asal);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Dosen  $dosen
     * @return \Illuminate\Http\Response
     */
    public function destroy(Dosen $dosen)
    {
        $dosen->delete();
        Alert::success('Berhasil',"Dosen $dosen->nama telah dihapus");
        return redirect('/dosens');
    }
}

resources/views/dosen/create.blade.php
@extends('layouts.app')
@section('content')
     <div class="pt-3">
          <h1 class="h2">Tambah Dosen</h1>
     </div>
     <hr>

     <form action="{{ route('dosens.store') }}" method="POST">
          @include('dosen.form',['tombol' => 'Tambah'])
     </form>
@endsection

resources/views/dosen/edit.blade.php
@extends('layouts.app')
@section('content')
     <div class="pt-3">
          <h1 class="h2">Edit Dosen</h1>
     </div>
     <hr>

     <form action="{{ route('dosens.update',['dosen' => $dosen->id]) }}" method="POST">
          @method('PATCH')
          @include('dosen.form',['tombol' => 'Update'])
     </form>
@endsection

resources/views/dosen/form.blade.php
@csrf
<div class="row mb-3">
     <label for="nid" class="col-md-3 col-form-label text-md-end" title="8 digit angka NID">Nomor Induk Dosen</label>
     <div class="col-md-4">
          <input type="text" name="nid" id="nid" class="form-control @error('nid') is-invalid @enderror" value="{{ old('nid') ?? $dosen->nid  ?? '' }}" placeholder="8 digit angka NID, contoh: 99754972" autofocus>
          @error('nid')
               <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
               </span>
          @enderror
     </div>
</div>

<div class="row mb-3">
     <label for="nama" class="col-md-3 col-form-label text-md-end">Nama Dosen</label>
     <div class="col-md-4">
          <input type="text" name="nama" id="nama" class="form-control @error('nama') is-invalid @enderror" value="{{ old('nama') ?? $dosen->nama  ?? '' }}" autofocus>
          @error('nama')
               <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
               </span>
          @enderror
     </div>
</div>

<div class="row mb-3">
     <label for="jurusan_id" class="col-md-3 col-form-label text-md-end">Jurusan</label>
     <div class="col-md-4">
          <select name="jurusan_id" id="jurusan_id" class="form-select @error('jurusan_id') is-invalid @enderror">
               @foreach ($jurusans as $jurusan)
                    @if ($jurusan->id == (old('jurusan_id') ?? $dosen->jurusan_id ?? ''))
                         <option value="{{ $jurusan->id }}" selected>{{ $jurusan->nama }}</option>
                    @else
                         <option value="{{ $jurusan->id }}">{{ $jurusan->nama }}</option>
                    @endif
               @endforeach
          </select>
          @error('jurusan_id')
               <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
               </span>
          @enderror
     </div>
</div>

@isset($dosen)
     <input type="hidden" name="url_asal" value="{{ old('url_asal') ?? url()->previous().'#row-'.$dosen->id }}">
@else
     <input type="hidden" name="url_asal" value="{{ old('url_asal') ?? url()->previous() }}">
@endisset

<div class="row">
     <div class="col-md-6 offset-md-3">
          <button type="submit" class="btn btn-primary">{{ $tombol }}</button>
     </div>
</div>

resources/views/dosen/index.blade.php
@extends('layouts.app')
@section('content')
     <h1 class="display-4 text-center my-5" id="judul">
          Data Dosen {{ $nama_jurusan ?? 'Universitas MIKAR' }}
     </h1>

     <div class="text-end pt-5 pb-4">
          @auth
               <a href="{{ route('dosens.create') }}" class="btn btn-info">Tambah Dosen</a>
          @endauth
     </div>

     <table class="table table-striped">
          <thead>
               <th>#</th>
               <th>NID</th>
               <th>Nama Dosen</th>
               <th>Jurusan Dosen</th>
               @auth
               <th>Action</th>
               @endauth
          </thead>
          <tbody>
               @foreach ($dosens as $dosen)
                    <tr id="row-{{ $dosen->id }}">
                         <th>{{ $dosens->firstItem() + $loop->iteration - 1 }}</th>
                         <td>{{ $dosen->nid }}</td>
                         <td>
                              <a href="{{ route('dosens.show',['dosen' => $dosen->id]) }}">{{ $dosen->nama }}</a>
                         </td>
                         <td>{{ $dosen->jurusan->nama }}</td>
                         @auth
                         <td>
                              <a href="{{ route('dosens.edit',['dosen' => $dosen->id]) }}" class="btn btn-secondary" title="Edit Dosen">Edit</a>
                              <form action="{{ route('dosens.destroy',['dosen' => $dosen->id]) }}" method="POST" class="d-inline">
                                   @csrf @method('DELETE')
                                   <button type="submit" title="Hapus Dosen" class="btn btn-danger shadow-none btn-hapus" data-name={{ $dosen->nama }}data-table="dosen">Hapus</button>
                              </form>
                         </td>
                         @endauth
                    </tr>
               @endforeach
          </tbody>
     </table>
     <div class="row">
          <div class="mx-auto mt-3">
               {{ $dosens->fragment('judul')->links() }}
          </div>
     </div>
@endsection

resources/views/dosen/show.blade.php
@extends('layouts.app')
@section('content')
     <div class='pt-3 d-flex align-items-center'>
          <h1 class="h2 me-4">Biodata Dosen</h1>
          @auth
               <a href="{{ route('dosens.edit',['dosen' => $dosen->id])}}"
               class="btn btn-secondary me-1" title="Edit Dosen">Edit</a>
               <form action="{{ route('dosens.destroy',
               ['dosen' => $dosen->id]) }}" method="POST" class="d-inline">
               @csrf @method('DELETE')
               <button type="submit" class="btn btn-danger shadow-none btn-hapus"
               title="Hapus Dosen" data-name="{{$dosen->nama}}" data-table="dosen">
               Hapus</button>
               </form>
          @endauth
     </div>
     <hr>
     <ul>
          <li>Nama : <strong>{{ $dosen->nama }}</strong></li>
          <li>NID : <strong>{{ $dosen->nid }}</strong></li>
          <li>Jurusan : <strong>{{ $dosen->jurusan->nama }}</strong></li>
     </ul>
     <p>Mengajar Matakuliah : </p>
     <ol>
          @foreach ($dosen->matakuliahs as $matakuliah)
               <li>
                    {{ $matakuliah->nama }}
                    <small>
                         (<a href="{{ route('matakuliahs.show',['matakuliah' => $matakuliah->id]) }}">{{ $matakuliah->kode }}</a> {{ $matakuliah->jumlah_sks }} SKS )
                    </small>
               </li>
          @endforeach
     </ol>
     @auth
          <a href="{{ route('buat-matakuliah',['dosen' => $dosen->id]) }}" class="btn btn-info" title="Buat Mata Kuliah">Buat Matakuliah</a>
     @endauth
@endsection