routes/web.php
<?php

use App\Http\Controllers\DosenController;
use App\Http\Controllers\JurusanController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\LogoutController;
use App\Http\Controllers\MahasiswaController;
use App\Http\Controllers\MatakuliahController;
use App\Http\Controllers\PencarianController;
use App\Models\Dosen;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/',[LoginController::class,'index']);

Route::get('/logout',[LoginController::class,'index']);

Route::resource('jurusans',JurusanController::class);

Route::resource('dosens',DosenController::class);

Route::resource('matakuliahs',MatakuliahController::class);

Route::resource('mahasiswas',MahasiswaController::class);

Route::get('/jurusan-dosen/{jurusan_id}',[JurusanController::class,'jurusanDosen'])->name('jurusan-dosen');

Route::get('/jurusan-mahasiswa/{jurusan_id}',[JurusanController::class,'jurusanMahasiswa'])->name('jurusan-mahasiswa');

Route::get('/jurusan-matakuliah/{jurusan_id}',[JurusanController::class,'jurusanMatakuliah'])->name('jurusan-matakuliah');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('/buat-matakuliah/{dosen}',[MatakuliahController::class,'buatMatakuliah'])->name('buat-matakuliah');

Route::get('/mahasiswas/ambil-matakuliah/{mahasiswa}',[MahasiswaController::class,'ambilMatakuliah'])->name('ambil-matakuliah');

Route::post('/mahasiswas/ambil-matakuliah/{mahasiswa}',[MahasiswaController::class,'prosesAmbilMatakuliah'])->name('proses-ambil-matakuliah');

Route::get('/matakuliahs/dafarkan-mahasiswa/{matakuliah}',[MatakuliahController::class,'daftarkanMahasiswa'])->name('daftarkan-mahasiswa');

Route::post('/matakuliahs/dafarkan-mahasiswa/{matakuliah}',[MatakuliahController::class,'prosesDaftarkanMahasiswa'])->name('proses-daftarkan-mahasiswa');

Route::get('/pencarian',[PencarianController::class,'index']);

Route::get('/pencarian/proses',[PencarianController::class,'proses']);

app/Models/Jurusan.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Jurusan extends Model
{
    use HasFactory;
    protected $fillable = ['nama','kepala_jurusan','daya_tampung'];

    public function dosens(){
        return $this->hasMany('App\Models\Dosen');
    }

    public function mahasiswas(){
        return $this->hasMany('App\Models\Mahasiswa');
    }

    public function matakuliahs(){
        return $this->hasMany('App\Models\Matakuliah');
    }
}

app/Http/Controllers/JurusanController.php
<?php

namespace App\Http\Controllers;

use App\Models\Dosen;
use App\Models\Jurusan;
use App\Models\Mahasiswa;
use App\Models\Matakuliah;
use Illuminate\Http\Request;
use RealRashid\SweetAlert\Facades\Alert;

class JurusanController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function __construct()
    {
        $this->middleware('auth')->except(['index', 'jurusanDosen', 'jurusanMahasiswa']);
    }

    public function index()
    {
        $jurusans = Jurusan::withCount('mahasiswas')->orderBy('nama')->get();
        return view('jurusan.index',['jurusans' => $jurusans]);
    }

    public function jurusanDosen($jurusan_id){
        $dosens = Dosen::where('jurusan_id',$jurusan_id)->orderBy('nama')->paginate(5);
        $nama_jurusan = Jurusan::find($jurusan_id)->nama;

        return view('dosen.index',[
            'dosens' => $dosens,
            'nama_jurusan' => $nama_jurusan
        ]);
    }

    public function jurusanMahasiswa($jurusan_id){
        $mahasiswas = Mahasiswa::where('jurusan_id',$jurusan_id)->orderBy('nama')->paginate(5);
        $nama_jurusan = Jurusan::find($jurusan_id)->nama;

        return view('mahasiswa.index',[
            'mahasiswas' => $mahasiswas,
            'nama_jurusan' => $nama_jurusan
        ]);
    }

    public function jurusanMatakuliah($jurusan_id){
        $matakuliahs = Matakuliah::where('jurusan_id',$jurusan_id)->orderBy('nama')->paginate(5);
        $nama_jurusan = Matakuliah::find($jurusan_id)->jurusan->nama;

        return view('matakuliah.index',[
            'matakuliahs' => $matakuliahs,
            'nama_jurusan' => $nama_jurusan,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('jurusan.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validateData = $request->validate(
            [
                'nama' => 'required',
                'kepala_jurusan' => 'required',
                'daya_tampung' => 'required|min:10|integer',
            ]
        );
        $jurusan = Jurusan::create($validateData);
        Alert::success('Berhasil!',"Jurusan $jurusan->nama berhasil dibuat");
        return redirect("jurusans#card-{$jurusan->id}");
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Jurusan  $jurusan
     * @return \Illuminate\Http\Response
     */
    public function show(Jurusan $jurusan)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Jurusan  $jurusan
     * @return \Illuminate\Http\Response
     */
    public function edit(Jurusan $jurusan)
    {
        return view('jurusan.edit',compact("jurusan"));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Jurusan  $jurusan
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Jurusan $jurusan)
    {
        $validateData = $request->validate(
            [
                'nama' => 'required',
                'kepala_jurusan' => 'required',
                'daya_tampung' => 'required|min:10|integer',
            ]
        );

        $jurusan->update($validateData);

        Alert::success('Berhasil',"Jurusan $jurusan->nama telah diupdate");

        return redirect("/jurusans#card-{$jurusan->id}");
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Jurusan  $jurusan
     * @return \Illuminate\Http\Response
     */
    public function destroy(Jurusan $jurusan)
    {
        $jurusan->delete();
        Alert::success('Berhasil',"Jurusan $jurusan->nama telah dihapus");
        return redirect('/jurusans');
    }
}

resources/views/jurusan/create.blade.php
@extends('layouts.app')
@section('content')
     <div class="pt-3">
          <h1 class="h2">Tambah Jurusan</h1>
     </div>
     <hr>
     <form action="{{ route('jurusans.store') }}" method="POST">
          @include('jurusan.form',['tombol' => "Tambah"])
     </form>
@endsection

resources/views/jurusan/edit.blade.php
@extends('layouts.app')
@section('content')
     <div class="pt-3">
          <h1 class="h2">Edit Jurusan</h1>
     </div>
     <hr>

     <form action="{{ route('jurusans.update',['jurusan' => $jurusan->id]) }}" method="POST">
          @method('PATCH')
          @include('jurusan.form',['tombol' => 'Update'])
     </form>
@endsection

resources/views/jurusan/form.blade.php
@csrf
<div class="row mb-3">
     <label for="nama" class="col-md-3 col-form-label text-md-end">Nama Jurusan</label>
     <div class="col-md-4">
          <input type="text" name="nama" id="nama" class="form-control @error('nama') is-invalid @enderror" value="{{ old('nama') ?? $jurusan->nama ?? '' }}" autofocus>
          @error('nama')
          <span class="invalid-feedback" role="alert">
               <strong>{{ $message }}</strong>
          </span>
     @enderror
     </div>
</div>

<div class="row mb-3">
     <label for="kepala_jurusan" class="col-md-3 col-form-label text-md-end">Nama Kepala Jurusan</label>
     <div class="col-md-4">
          <input type="text" name="kepala_jurusan" id="kepala_jurusan" class="form-control @error('kepala_jurusan') is-invalid @enderror" value="{{ old('kepala_jurusan') ?? $jurusan->kepala_jurusan ?? '' }}" autofocus>
          @error('kepala_jurusan')
          <span class="invalid-feedback" role="alert">
               <strong>{{ $message }}</strong>
          </span>
     @enderror
     </div>
</div>

<div class="row mb-3">
     <label for="daya_tampung" class="col-md-3 col-form-label text-md-end">Daya Tampung</label>
     <div class="col-md-4">
          <input type="text" name="daya_tampung" id="daya_tampung" class="form-control @error('daya_tampung') is-invalid @enderror w-25" value="{{ old('daya_tampung') ?? $jurusan->daya_tampung ?? '' }}" autofocus>
          @error('daya_tampung')
          <span class="invalid-feedback" role="alert">
               <strong>{{ $message }}</strong>
          </span>
     @enderror
     </div>
</div>

<div class="row">
     <div class="col-md-6 offset-md-3">
          <button type="submit" class="btn btn-primary">{{ $tombol }}</button>
     </div>
</div>

resources/views/jurusan/index.blade.php
@extends('layouts.app')

@section('content')
    <h1 class="display-4 text-center my-5">Sistem Informasi Mikar</h1>

    <div class="text-end pt-5 pb-4">
        @auth
            <a href="{{ route('jurusans.create') }}" class="btn btn-info">Tambah Jurusan</a>
        @endauth
    </div>

    <div class="row row-cols-1 row-cols-md-2 row-cols-xl-3 g-4">
        @foreach ($jurusans as $jurusan)
            <div class="col" id=card-{{ $jurusan->id }}>
                <div class="card h-100">
                    @auth
                        <div class="btn-group btn-action">
                            <a href="{{ route('jurusans.edit', ['jurusan' => $jurusan->id]) }}"
                                class="btn btn-primary d-inline-block" title="Edit Jurusan"><i class="fa fa-edit fa-fw"></i></a>
                            <form action="{{ route('jurusans.destroy', ['jurusan' => $jurusan->id]) }}" method="POST">
                                @csrf @method('DELETE')
                                <button type="submit" class="btn btn-danger shadow-none btn-hapus" title="Hapus Jurusan"
                                    data-name="{{ $jurusan->nama }}" data-table="jurusan"><i
                                        class="fa fa-trash fa-fw"></i></button>
                            </form>
                        </div>
                    @endauth
                    <div class="card-body text-center">
                        <h3 class="card-title py-1">{{ $jurusan->nama }}</h3>
                        <hr>
                        <div class="card-text py-1">Kepala Jurusan :
                            <b>{{ $jurusan->kepala_jurusan }}</b>
                        </div>
                        <div class="card-text pb-4">
                            Total Mahasiswa : {{ $jurusan->mahasiswas_count }} (daya tampung {{ $jurusan->daya_tampung }})
                        </div>
                        <a href="{{ route('jurusan-dosen', ['jurusan_id' => $jurusan->id]) }}"
                            class="btn btn-info d-block">Dosen</a>
                        <a href="{{ route('jurusan-mahasiswa', ['jurusan_id' => $jurusan->id]) }}"
                            class="btn btn-success d-block mt-2">Mahasiswa</a>
                        <a href="{{ route('jurusan-matakuliah', ['jurusan_id' => $jurusan->id]) }}"
                            class="btn btn-success d-block mt-2">Matakuliah</a>
                    </div>
                </div>
            </div>
        @endforeach
    </div>
@endsection