routes/web.php
<?php

use App\Http\Controllers\DosenController;
use App\Http\Controllers\JurusanController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\LogoutController;
use App\Http\Controllers\MahasiswaController;
use App\Http\Controllers\MatakuliahController;
use App\Http\Controllers\PencarianController;
use App\Models\Dosen;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/',[LoginController::class,'index']);

Route::get('/logout',[LoginController::class,'index']);

Route::resource('jurusans',JurusanController::class);

Route::resource('dosens',DosenController::class);

Route::resource('matakuliahs',MatakuliahController::class);

Route::resource('mahasiswas',MahasiswaController::class);

Route::get('/jurusan-dosen/{jurusan_id}',[JurusanController::class,'jurusanDosen'])->name('jurusan-dosen');

Route::get('/jurusan-mahasiswa/{jurusan_id}',[JurusanController::class,'jurusanMahasiswa'])->name('jurusan-mahasiswa');

Route::get('/jurusan-matakuliah/{jurusan_id}',[JurusanController::class,'jurusanMatakuliah'])->name('jurusan-matakuliah');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('/buat-matakuliah/{dosen}',[MatakuliahController::class,'buatMatakuliah'])->name('buat-matakuliah');

Route::get('/mahasiswas/ambil-matakuliah/{mahasiswa}',[MahasiswaController::class,'ambilMatakuliah'])->name('ambil-matakuliah');

Route::post('/mahasiswas/ambil-matakuliah/{mahasiswa}',[MahasiswaController::class,'prosesAmbilMatakuliah'])->name('proses-ambil-matakuliah');

Route::get('/matakuliahs/dafarkan-mahasiswa/{matakuliah}',[MatakuliahController::class,'daftarkanMahasiswa'])->name('daftarkan-mahasiswa');

Route::post('/matakuliahs/dafarkan-mahasiswa/{matakuliah}',[MatakuliahController::class,'prosesDaftarkanMahasiswa'])->name('proses-daftarkan-mahasiswa');

Route::get('/pencarian',[PencarianController::class,'index']);

Route::get('/pencarian/proses',[PencarianController::class,'proses']);

app/Models/Matakuliah.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Matakuliah extends Model
{
    use HasFactory;
    protected $fillable = ['kode','nama','jurusan_id','dosen_id','jumlah_sks'];

    public function jurusan(){
        return $this->belongsTo('App\Models\Jurusan');
    }

    public function dosen(){
        return $this->belongsTo('App\Models\Dosen');
    }

    public function mahasiswas(){
        return $this->belongsToMany('App\Models\Mahasiswa')->withTimestamps();
    }
}

app/Http/Controllers/MatakuliahController.php
<?php

namespace App\Http\Controllers;

use App\Models\Dosen;
use App\Models\Jurusan;
use App\Models\Mahasiswa;
use App\Models\Matakuliah;
use Illuminate\Http\Request;
use RealRashid\SweetAlert\Facades\Alert;

class MatakuliahController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function __construct()
    {
        $this->middleware('auth')->except(['index','show']);
    }
    
    public function index()
    {
        $matakuliahs = Matakuliah::with('jurusan','dosen')->orderBy('nama')->paginate(10);
        return view('matakuliah.index',['matakuliahs' => $matakuliahs]);
    }

    public function buatMatakuliah(Dosen $dosen)
    {
        $jurusans = Jurusan::orderBy('nama')->get();
        return view('matakuliah.create',[
            'dosen' => $dosen,
            'jurusans' => $jurusans,
        ]);
    }

    public function daftarkanMahasiswa(Matakuliah $matakuliah){
        $mahasiswas = Mahasiswa::where('jurusan_id',$matakuliah->jurusan_id)->orderBy('nama')->get();

        $mahasiswas_sudah_terdaftar = $matakuliah->mahasiswas->pluck('id')->all();

        return view('matakuliah.daftarkan-mahasiswa',
            [
                'matakuliah' => $matakuliah,
                'mahasiswas' => $mahasiswas,
                'mahasiswas_sudah_terdaftar' => $mahasiswas_sudah_terdaftar
            ]
        );
    }

    public function prosesDaftarkanMahasiswa(Request $request, Matakuliah $matakuliah){
        $mahasiswa_jurusan = Mahasiswa::where('jurusan_id',$matakuliah->jurusan_id)->pluck('id')->toArray();

        $validateData = $request->validate(
            [
                'mahasiswa.*' => 'distinct|in:'.implode(',',$mahasiswa_jurusan),
            ]
        );

        $matakuliah->mahasiswas()->sync($validateData['mahasiswa'] ?? []);

        Alert::success('Berhasil','Terdapat '.count($validateData['mahasiswa'] ?? [])." mahasiswa yang mengambil $matakuliah->nama");

        return redirect(route('matakuliahs.show',['matakuliah' => $matakuliah->id]));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $jurusans = Jurusan::orderBy('nama')->get();
        $dosens = Dosen::orderBy('nama')->get();
        return view('matakuliah.create',[
            'jurusans' => $jurusans,
            'dosens' => $dosens,
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validateData = $request->validate(
            [
                'kode' => 'required|alpha_num|size:5|unique:matakuliahs,kode',
                'nama' => 'required',
                'dosen_id' => 'required|exists:App\Models\Dosen,id',
                'jurusan_id' => 'required|exists:App\Models\Jurusan,id',
                'jumlah_sks' => 'required|digits_between:1,6',
            ]
        );
        Matakuliah::create($validateData);
        Alert::success('Berhasil',"Matakuliah $request->nama berhasil dibuat");
        return redirect($request->url_asal);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Matakuliah  $matakuliah
     * @return \Illuminate\Http\Response
     */
    public function show(Matakuliah $matakuliah)
    {
        $mahasiswas = $matakuliah->mahasiswas->sortBy('nama');

        return view('matakuliah.show',[
            'matakuliah' => $matakuliah,
            'mahasiswas' => $mahasiswas
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Matakuliah  $matakuliah
     * @return \Illuminate\Http\Response
     */
    public function edit(Matakuliah $matakuliah)
    {
        $jurusans = Jurusan::orderBy('nama')->get();
        $dosens = Dosen::orderBy('nama')->get();

        return view('matakuliah.edit',
        [
            'matakuliah' => $matakuliah,
            'dosens' => $dosens,
            'jurusans' => $jurusans
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Matakuliah  $matakuliah
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Matakuliah $matakuliah)
    {
        $validateData = $request->validate(
            [
                'kode' => 'required|alpha_num|size:5|unique:matakuliahs,kode,'.$matakuliah->id,
                'nama' => 'required',
                'dosen_id' => 'required|exists:App\Models\Dosen,id',
                'jurusan_id' => 'required|exists:App\Models\Jurusan,id',
                'jumlah_sks' => 'required|digits_between:1,6'
            ]
        );

        if (($matakuliah->mahasiswas()->count() > 0) && ($matakuliah->jurusan_id != $request->jurusan_id)) {
            Alert::error('Gagal','Jurusan tidak bisa diubah');
            return back();
        }

        $matakuliah->update($validateData);
        Alert::success('Berhasil',"Matakuliah $request->nama telah diupdate");
        return redirect($request->url_asal);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Matakuliah  $matakuliah
     * @return \Illuminate\Http\Response
     */
    public function destroy(Matakuliah $matakuliah)
    {
        $matakuliah->delete();
        Alert::success('Berhasil',"Matakuliah $matakuliah->nama telah dihapus");
        return redirect('/matakuliahs');
    }
}

resources/views/matakuliah/create.blade.php
@extends('layouts.app')
@section('content')

<div class="pt-3">
  <h1 class="h2">Tambah Mata Kuliah</h1>
</div>
<hr>

<form method="POST" action="{{ route('matakuliahs.store') }}">
  @include('matakuliah.form',['tombol' => 'Tambah'])
</form>

@endsection

resources/views/matakuliah/daftarkan-mahasiswa.blade.php
@extends('layouts.app')
@section('content')
     <div class="pt-3">
          <h1 class="h2">Daftarkan Mahasiswa ke Mata Kuliah</h1>
     </div>
     <hr>
     <ul>
          <li>Nama : <strong>{{ $matakuliah->nama }}</strong></li>
          <li>Kode Mata Kuliah : <strong>{{ $matakuliah->kode }}</strong></li>
          <li>Dosen Pengajar :
               <strong>
                    <a href="{{ route('dosens.show',['dosen' => $matakuliah->dosen->id]) }}">{{ $matakuliah->dosen->nama }}</a>
               </strong>
          </li>
          <li>Jurusan : <strong>{{ $matakuliah->jurusan->nama }}</strong></li>
          <li>Jumlah SKS : <strong>{{ $matakuliah->jumlah_sks }}</strong></li>
          <li>Total Mahasiswa : 
               <strong>{{ count($mahasiswas_sudah_terdaftar) }}</strong>
          </li>
     </ul>
     <hr>
     <h5 class="mt-5 mb-4">Daftar mahasiswa {{ $matakuliah->jurusan->nama }} yang mengambil mata kuliah {{ $matakuliah->nama }}</h5>
     <form action="{{ route('proses-daftarkan-mahasiswa',['matakuliah' => $matakuliah->id]) }}" method="POST">
          @csrf
          <div class="form-group row">
               @error('mahasiswa.*')
                    <div class="invalid-feedback my-3 d-block ml-3">
                         <strong>Error : Pilihan mahasiswa ada yang berulang / bukan dari {{ $matakuliah->jurusan->nama }}</strong>
                    </div>
               @enderror
               <div class="col-md-12">
                    @foreach ($mahasiswas as $mahasiswa)
                         <div class="custom-control custom-checkbox mb-2">
                              <input type="checkbox" name="mahasiswa[]" id="mahasiswa{{ $mahasiswa->id }}" value="{{ $mahasiswa->id }}" @if (in_array($mahasiswa->id,(old('mahasiswa') ?? $mahasiswas_sudah_terdaftar ?? [] )))
                                   checked
                              @endif>
                              <label  class="custom-control-label" for="mahasiswa{{ $mahasiswa->id }}">
                                   {{ $mahasiswa->nama }}
                                   <small>
                                        (<a href="{{ route('mahasiswas.show',['mahasiswa' => $mahasiswa->id]) }}">{{ $mahasiswa->nim }}</a>)
                                   </small>
                              </label>
                         </div>
                    @endforeach
               </div>
          </div>

          <div class="form-group row mt-4">
               <div class="col-md-6">
                    <button  type="submit" class="btn btn-primary">Daftarkan</button>
               </div>
          </div> 
     </form>
@endsection

resources/views/matakuliah/edit.blade.php
@extends('layouts.app')
@section('content')
     <div class="pt-3">
          <h1 class="h2">Edit Mata Kuliah</h1>
     </div>
     <hr>
     <form action="{{ route('matakuliahs.update',['matakuliah' => $matakuliah->id]) }}" method="POST">
          @method('PATCH')
          @include('matakuliah.form',['tombol' => 'Update'])
     </form>
@endsection

resources/views/matakuliah/form.blade.php
@csrf
<div class="row mb-3">
     <label for="kode" class="col-md-3 col-form-label text-md-end" title="5 digit kode matakuliah">Kode Matakuliah</label>
     <div class="col-md-4">
          <input type="text" name="kode" id="kode" class="form-control @error('kode') is-invalid @enderror" value="{{ old('kode') ?? $matakuliah->kode ?? '' }}" placeholder="5 kode mata kuliah, contoh: IX264" autofocus>
          @error('kode')
               <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
               </span>
          @enderror
     </div>
</div>

<div class="row mb-3">
     <label for="nama" class="col-md-3 col-form-label text-md-end">Nama Matakuliah</label>
     <div class="col-md-4">
          <input type="text" name="nama" id="nama" class="form-control @error('nama') is-invalid @enderror" value="{{ old('nama') ?? $matakuliah->nama ?? '' }}">
          @error('nama')
               <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
               </span>
          @enderror
     </div>
</div>

<div class="row mb-3">
     <label for="jurusan_id" class="col-md-3 col-form-label text-md-end">Jurusan</label>
     @if (($tombol == 'Update') && ($matakuliah->mahasiswas->count() > 0 ))
          <div class="col-md-9 d-flex align-items-center">
               <div>{{ $matakuliah->jurusan->nama }}
                    <small><i>(tidak bisa diubah karena sudah diambil {{ $matakuliah->mahasiswas->count() }} mahasiswa)</i></small>
               </div>
          </div>
          <input type="hidden" name="jurusan_id" id="jurusan_id" value="{{ $matakuliah->jurusan_id }}">
     @else
          <div class="col-md-4">
          <select name="jurusan_id" id="jurusan_id" class="form-select @error('jurusan_id') is-invalid @enderror">
               @foreach ($jurusans as $jurusan)
               @if ($jurusan->id == (old('jurusan_id') ?? $dosen->jurusan_id ?? ''))
                    <option value="{{ $jurusan->id }}" selected>{{ $jurusan->nama }}</option>
               @else
                    <option value="{{ $jurusan->id }}">{{ $jurusan->nama }}</option>
               @endif
               @endforeach
          </select>
          @error('jurusan_id')
               <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
               </span>
          @enderror
     </div>
     @endif
</div>

<div class="row mb-3">
     <label for="dosen_id" class="col-md-3 col-form-label text-md-end">Dosen Pengajar</label>
          @if (isset($dosen))
               <div class="col-md-4 d-flex align-items-center">
                    <div>{{ $dosen->nama }}</div>
               </div>
               <input type="hidden" name="dosen_id" id="dosen_id" value="{{ $dosen->id }}">
          @else
               <div class="col-md-4">
                    <select name="dosen_id" id="dosen_id" class="form-select @error('dosen_id') is-invalid @enderror">
                    @foreach ($dosens as $dosen)
                    @if ($dosen->id == (old('dosen_id') ?? $matakuliah->dosen->id ?? ''))
                         <option value="{{ $dosen->id }}" selected>{{ $dosen->nama }}</option>
                    @else
                         <option value="{{ $dosen->id }}">{{ $dosen->nama }}</option>
                    @endif
                    @endforeach
               </select>
               </div>
          @endif
          @error('dosen_id')
               <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
               </span>
          @enderror
</div>

<div class="row mb-3">
     <label for="jumlah_sks" class="col-md-3 col-form-label text-md-end">Jumlah SKS</label>
     <div class="col-md-4">
          <select name="jumlah_sks" id="jumlah_sks" class="form-select @error('jumlah_sks') is-invalid @enderror">
               @for ($i = 1; $i <= 6; $i++)
                    @if($i == (old('jumlah_sks') ?? $matakuliah->jumlah_sks ?? ''))
                         <option value="{{ $i }}" selected>{{ $i }}</option>
                    @else
                         <option value="{{ $i }}">{{ $i }}</option>
                    @endif
               @endfor
          </select>
          @error('jumlah_sks')
               <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
               </span>
          @enderror
     </div>
</div>

@isset($matakuliah)
     <input type="hidden" name="url_asal" value="{{ old('url_asal') ?? url()->previous().'#row-'.$matakuliah->id}}">
@else
<input type="hidden" name="url_asal" value="{{ old('url_asal') ?? url()->previous()}}">
@endisset

<div class="row">
     <div class="col-md-6 offset-md-3">
          <button type="submit" class="btn btn-primary">{{ $tombol }}</button>
     </div>
</div>

resources/views/matakuliah/index.blade.php
@extends('layouts.app')
@section('content')
     <h1 class="display-4 text-center my-5" id="judul">
          Matakuliah {{ $nama_jurusan ?? 'Universitas MIKAR' }}
     </h1>

     <div class="text-end pt-5 pb-4">
          @auth
               <a href="{{ route('matakuliahs.create') }}" class="btn btn-info">Tambah Matakuliah</a>
          @endauth
     </div>

     <table class="table table-striped">
          <thead>
               <tr>
                    <th>#</th>
                    <th>Kode</th>
                    <th>Nama Matakuliah</th>
                    <th>Dosen Pengajar</th>
                    <th>Jumlah SKS</th>
                    <th>Jurusan</th>
                    @auth
                    <th>Action</th>
                    @endauth
               </tr>
          </thead>
          <tbody>
               @foreach ($matakuliahs as $matakuliah)
                    <tr id="row-{{ $matakuliah->id }}">
                         <th>{{ $matakuliahs->firstItem() + $loop->iteration - 1  }}</th>
                         <td>{{ $matakuliah->kode }}</td>
                         <td>
                              <a href="{{ route('matakuliahs.show',['matakuliah' => $matakuliah->id]) }}">{{ $matakuliah->nama }}</a>
                         </td>
                         <td>
                              <a href="{{ route('dosens.show',['dosen' => $matakuliah->dosen->id]) }}">{{ $matakuliah->dosen->nama }}</a>
                         </td>
                         <td>{{ $matakuliah->jumlah_sks }}</td>
                         <td>{{ $matakuliah->jurusan->nama }}</td>
                         @auth
                         <td>
                              <a href="{{ route('matakuliahs.edit',['matakuliah' => $matakuliah->id]) }}" class="btn btn-secondary" title="Edit Matakuliah">Edit</a>
                              <form action="{{ route('matakuliahs.destroy',['matakuliah' => $matakuliah->id]) }}" method="POST" class="d-inline">
                                   @csrf @method('DELETE')
                                   <button type="submit" class="btn btn-danger shadow-none btn-hapus" title="Hapus Matakuliah" data-name="{{ $matakuliah->nama }}">Hapus</button>
                              </form>
                         </td>
                         @endauth
                    </tr>
               @endforeach
          </tbody>
     </table>
     <div class="row">
          <div class="mx-auto mt-3">
               {{ $matakuliahs->fragment('judul')->links() }}
          </div>
     </div>
@endsection

resources/views/matakuliah/show.blade.php
@extends('layouts.app')
@section('content')
     <div class="pt-3 d-flex align-items-center">
          <h1 class="h2 me-4">Informasi Matakuliah</h1>
          @auth
               <a href="{{ route('matakuliahs.edit',['matakuliah' => $matakuliah->id])}}"
               class="btn btn-secondary me-1" title="Edit Matakuliah">Edit</a>
               <form action="{{ route('matakuliahs.destroy',
               ['matakuliah' => $matakuliah->id]) }}" method="POST" class="d-inline">
               @csrf @method('DELETE')
               <button type="submit" class="btn btn-danger shadow-none btn-hapus"
               title="Hapus Matakuliah" data-name="{{$matakuliah->nama}}" data-table="matakuliah">
               Hapus</button>
               </form>
          @endauth
     </div>
     <hr>
     <ul>
          <li>Nama : <strong>{{ $matakuliah->nama }}</strong></li>
          <li>Kode Matakuliah : <strong>{{ $matakuliah->kode }}</strong></li>
          <li>Dosen Pengajar : 
               <strong>
                    <a href="{{ route('dosens.show',['dosen' => $matakuliah->dosen->id]) }}">{{ $matakuliah->dosen->nama }}</a>
               </strong>
          </li>
          <li>Jurusan : <strong>{{ $matakuliah->jurusan->nama }}</strong></li>
          <li>Jumlah SKS : <strong>{{ $matakuliah->jumlah_sks }}</strong></li>
          <li>Total Mahasiswa : <strong>{{ count($mahasiswas) }}</strong></li>
     </ul>
     <p>Daftar Mahasiswa : </p>
     <ol>
          @foreach ($mahasiswas as $mahasiswa)
               <li>
                    {{ $mahasiswa->nama }}
                    <small>
                         (<a href="{{ route('mahasiswas.show',['mahasiswa' => $mahasiswa->id]) }}">{{ $mahasiswa->nim }}</a>)
                    </small>
               </li>
          @endforeach
     </ol>
     @auth
          <a href="{{ route('daftarkan-mahasiswa',['matakuliah' => $matakuliah->id]) }}" class="btn btn-info" title="Daftakan Mahasiswa">Daftakan Mahasiswa</a>
     @endauth
@endsection