routes/web.php
<?php

use App\Http\Controllers\DosenController;
use App\Http\Controllers\JurusanController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\LogoutController;
use App\Http\Controllers\MahasiswaController;
use App\Http\Controllers\MatakuliahController;
use App\Http\Controllers\PencarianController;
use App\Models\Dosen;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/',[LoginController::class,'index']);

Route::get('/logout',[LoginController::class,'index']);

Route::resource('jurusans',JurusanController::class);

Route::resource('dosens',DosenController::class);

Route::resource('matakuliahs',MatakuliahController::class);

Route::resource('mahasiswas',MahasiswaController::class);

Route::get('/jurusan-dosen/{jurusan_id}',[JurusanController::class,'jurusanDosen'])->name('jurusan-dosen');

Route::get('/jurusan-mahasiswa/{jurusan_id}',[JurusanController::class,'jurusanMahasiswa'])->name('jurusan-mahasiswa');

Route::get('/jurusan-matakuliah/{jurusan_id}',[JurusanController::class,'jurusanMatakuliah'])->name('jurusan-matakuliah');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('/buat-matakuliah/{dosen}',[MatakuliahController::class,'buatMatakuliah'])->name('buat-matakuliah');

Route::get('/mahasiswas/ambil-matakuliah/{mahasiswa}',[MahasiswaController::class,'ambilMatakuliah'])->name('ambil-matakuliah');

Route::post('/mahasiswas/ambil-matakuliah/{mahasiswa}',[MahasiswaController::class,'prosesAmbilMatakuliah'])->name('proses-ambil-matakuliah');

Route::get('/matakuliahs/dafarkan-mahasiswa/{matakuliah}',[MatakuliahController::class,'daftarkanMahasiswa'])->name('daftarkan-mahasiswa');

Route::post('/matakuliahs/dafarkan-mahasiswa/{matakuliah}',[MatakuliahController::class,'prosesDaftarkanMahasiswa'])->name('proses-daftarkan-mahasiswa');

Route::get('/pencarian',[PencarianController::class,'index']);

Route::get('/pencarian/proses',[PencarianController::class,'proses']);

app/Models/Mahasiswa.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Mahasiswa extends Model
{
    use HasFactory;
    protected $fillable = ['nim','nama','jurusan_id'];

    public function jurusan() {
        return $this->belongsTo('App\Models\Jurusan');
    }

    public function matakuliahs() {
        return $this->belongsToMany('App\Models\Matakuliah')->withTimestamps();
    }
}

app/Http/Controllers/MahasiswaController.php
<?php

namespace App\Http\Controllers;

use App\Models\Jurusan;
use App\Models\Mahasiswa;
use App\Models\Matakuliah;
use Illuminate\Http\Request;
use RealRashid\SweetAlert\Facades\Alert;

class MahasiswaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function __construct()
    {
        $this->middleware('auth')->except(['index','show']);
    }
    
    public function index()
    {
        $mahasiswas = Mahasiswa::with('jurusan')->orderBy('nama')->paginate(10);
        return view('mahasiswa.index',['mahasiswas' => $mahasiswas]);
    }

    public function ambilMatakuliah(Mahasiswa $mahasiswa) 
    {
        $matakuliahs = Matakuliah::where('jurusan_id',$mahasiswa->jurusan_id)->orderBy('nama')->get();

        $matakuliahs_sudah_diambil = $mahasiswa->matakuliahs->pluck('id')->all();

        return view('mahasiswa.ambil-matakuliah',[
            'mahasiswa' => $mahasiswa,
            'matakuliahs' => $matakuliahs,
            'matakuliahs_sudah_diambil' => $matakuliahs_sudah_diambil,
        ]);
    }

    public function prosesAmbilMatakuliah(Request $request,Mahasiswa $mahasiswa){
        $matakuliah_jurusan = Matakuliah::where('jurusan_id',$mahasiswa->jurusan_id)->pluck('id')->toArray();

        $validateData = $request->validate(
            [
                'matakuliah.*' => 'distinct|in:'.implode(',',$matakuliah_jurusan)
            ]
        );

        $mahasiswa->matakuliahs()->sync($validateData['matakuliah'] ?? []);

        Alert::success("Berhasil","Terdapat ".count($validateData['matakuliah'] ?? [])." matakuliah yang diambil $mahasiswa->nama");

        return redirect(route('mahasiswas.show',['mahasiswa' => $mahasiswa->id]));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $jurusans = Jurusan::orderBy('nama')->get();
        return view('mahasiswa.create',compact('jurusans'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validateData = $request->validate(
            [
                'nim' => "required|alpha_num|size:8|unique:mahasiswas,nim",
                'nama' => "required",
                'jurusan_id' => "required|exists:App\Models\Jurusan,id",
            ]
        );

        $total_mahasiswa = Mahasiswa::where('jurusan_id',$request->jurusan_id)->count();
        $daya_tampung = Jurusan::find($request->jurusan_id)->daya_tampung;
        if ($total_mahasiswa >= $daya_tampung){
            Alert::error('Pendaftaran Gagal','Sudah melebihi daya tampung jurusan');
            return back()->withInput();
        }

        Mahasiswa::create($validateData);
        Alert::success('Berhasil',"Mahasiswas $request->nama berhasil dibuat");
        return redirect($request->url_asal);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Mahasiswa  $mahasiswa
     * @return \Illuminate\Http\Response
     */
    public function show(Mahasiswa $mahasiswa)
    {
        $matakuliahs = $mahasiswa->matakuliahs->sortBy('nama');
        return view('mahasiswa.show',[
            'mahasiswa' => $mahasiswa,
            'matakuliahs' => $matakuliahs,
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Mahasiswa  $mahasiswa
     * @return \Illuminate\Http\Response
     */
    public function edit(Mahasiswa $mahasiswa)
    {
        $jurusans = Jurusan::orderBy('nama')->get();
        return view('mahasiswa.edit',[
            'jurusans' => $jurusans,
            'mahasiswa' => $mahasiswa
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Mahasiswa  $mahasiswa
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Mahasiswa $mahasiswa)
    {
        $validateData = $request->validate(
            [
                'nim' => 'required|alpha_num|size:8|unique:mahasiswas,nim,'.$mahasiswa->id,
                'nama' => 'required',
                'jurusan_id' => 'required|exists:App\Models\Jurusan,id'
            ]
        );

        if (($mahasiswa->matakuliahs()->count() > 0 ) && ($mahasiswa->jurusan_id != $request->jurusan_id)) {
            Alert::error('Gagal','Jurusan tidak bisa diubah');
            return back()->withInput();
        }

        $mahasiswa->update($validateData);
        Alert::success('Berhasil',"Mahasiswa $request->nama telah diupdate");
        return redirect($request->url_asal);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Mahasiswa  $mahasiswa
     * @return \Illuminate\Http\Response
     */
    public function destroy(Mahasiswa $mahasiswa)
    {
        $mahasiswa->delete();
        Alert::success('Berhasil',"Mahasiswa $mahasiswa->nama telah dihapus");
        return redirect('/mahasiswas');
    }
}

resources/views/mahasiswa/ambil-matakuliah.blade.php
@extends('layouts.app')
@section('content')
     <div class="pt-3">
          <h1 class="h2">Ambil Matakuliah Untuk Mahasiswa</h1>
     </div>
     <hr>
     <ul>
          <li>Nama : <strong>{{ $mahasiswa->nama }}</strong></li>
          <li>Nomor Induk Mahasiswa : <strong>{{ $mahasiswa->nim }}</strong></li>
          <li>Jurusan : <strong>{{ $mahasiswa->jurusan->nama }}</strong></li>
          <li>Total Matakuliah : 
               <strong>{{ $mahasiswa->matakuliahs->count() }}
                         ({{ $mahasiswa->matakuliahs->sum('jumlah_sks') }} sks)
               </strong>
          </li>
          <hr>
          <h5 class="my-4">Daftar Matakuliah {{ $mahasiswa->jurusan->nama }} yang diambil oleh {{ $mahasiswa->nama }} :</h5>
          <form method="POST" action="{{ route('proses-ambil-matakuliah',['mahasiswa' => $mahasiswa->id]) }}">
               @csrf
               <div class="row">
                    @error('matakuliah.*')
                         <div class="invalid-feedback my-3 d-block">
                              <strong>Error: Pilihan mata kuliah ada yang berulang / bukan dari jurusan {{ $mahasiswa->jurusan->nama }}!</strong>
                         </div>
                    @enderror
                    <div class="col-md-12">
                         @foreach ($matakuliahs as $matakuliah)
                              <div class="mb-2">
                                   <input type="checkbox" name="matakuliah[]" id="matakuliah-{{ $matakuliah->id }}" class="form-check-input" value="{{ $matakuliah->id }}" @if (in_array($matakuliah->id,(old('matakuliah') ?? $matakuliahs_sudah_diambil ?? [] )))
                                        checked
                                   @endif>
                                   <label for= "matakuliah-{{ $matakuliah->id }}" class="form-check-label ms-1">
                                        {{ $matakuliah->nama }}
                                        <small>
                                             (<a href="{{ route('matakuliahs.show',['matakuliah' => $matakuliah->id]) }}">{{ $matakuliah->kode }}</a>)
                                        </small>
                                   </label>
                              </div>
                         @endforeach
                    </div>
               </div>

               <div class="row mt-4">
                    <div class="col-md-6">
                         <button class="btn btn-primary" type="submit">Daftarkan</button>
                    </div>
               </div>
          </form>
     </ul>
@endsection

resources/views/mahasiswa/create.blade.php
@extends('layouts.app')
@section('content')
     <div class="pt-3">
          <h1 class="h2">Tambah Mahasiswa</h1>
     </div>
     <hr>
     <form action="{{ route('mahasiswas.store') }}" method="POST">
          @include('mahasiswa.form',['tombol' => 'Tambah'])
     </form>
@endsection

resources/views/mahasiswa/edit.blade.php
@extends('layouts.app')
@section('content')
     <div class="pt-3">
          <h1 class="h2">Edit Mahasiswa</h1>
     </div>
     <hr>

     <form action="{{ route('mahasiswas.update',['mahasiswa' => $mahasiswa->id]) }}" method="POST">
          @method('PATCH')
          @include('mahasiswa.form',['tombol' => 'Update'])
     </form>
@endsection

resources/views/mahasiswa/form.blade.php
@csrf
<div class="row mb-3">
     <label for="nim" class="col-md-3 col-form-label text-md-end">Nomor Induk Mahasiswa</label>
     <div class="col-md-4">
          <input type="text" name="nim" id="nim" class="form-control @error('nim') is-invalid @enderror" value="{{ old('nim') ?? $mahasiswa->nim ?? '' }}" placeholder="8 digit angka NIM, contoh: 10311492" autofocus>
          @error('nim')
               <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
               </span>
          @enderror
     </div>
</div>

<div class="row mb-3">
     <label for="nama" class="col-md-3 col-form-label text-md-end">Nama Mahasiswa</label>
     <div class="col-md-4">
          <input type="text" name="nama" id="nama" class="form-control @error('nama') is-invalid @enderror" value="{{ old('nama') ?? $mahasiswa->nama ?? '' }}">
          @error('nama')
               <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
               </span>
          @enderror
     </div>
</div>

<div class="row mb-3">
     <label for="jurusan_id" class="col-md-3 col-form-label text-md-end">Jurusan</label>
     @if (($tombol == 'Update') && ($mahasiswa->matakuliahs->count() > 0 ))
          <div class="col-md-9 d-flex align-items-center">
               <div>{{ $mahasiswa->jurusan->nama }}
                    <small><i>(tidak bisa diubah karena sudah mengambil {{ $mahasiswa->matakuliahs->count() }} mata kuliah)</i></small>
               </div>
          </div>
          <input type="hidden" name="jurusan_id" id="jurusan_id" value="{{ $mahasiswa->jurusan_id }}">
     @else
          <div class="col-md-4">
          <select name="jurusan_id" id="jurusan_id" class="form-select @error('jurusan_id') is-invalid @enderror">
               @foreach ($jurusans as $jurusan)
                    @if ($jurusan->id == (old('jurusan_id') ?? $dosen->jurusan_id ?? ''))
                         <option value="{{ $jurusan->id }}" selected>{{ $jurusan->nama }}</option>
                    @else
                         <option value="{{ $jurusan->id }}">{{ $jurusan->nama }}</option>
                    @endif
               @endforeach
          </select>
          @error('jurusan_id')
               <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
               </span>
          @enderror
     </div>
     @endif
</div>

@isset($mahasiswa)
     <input type="hidden" name="url_asal" value="{{ old('url_asal') ?? url()->previous().'#row-'.$mahasiswa->id }}">
@else
     <input type="hidden" name="url_asal" value="{{ old('url_asal') ?? url()->previous() }}">
@endisset

<div class="row">
     <div class="col-md-6 offset-md-3">
          <button type="submit" class="btn btn-primary">{{ $tombol }}</button>
     </div>
</div>

resources/views/mahasiswa/index.blade.php
@extends('layouts.app')
@section('content')
     <h1 class="display-4 text-center my-5" id="judul">
          Mahasiswa {{ $nama_jurusan ?? 'Universitas MIKAR' }}
     </h1>

     <div class="text-end pt-5 pb-4">
          @auth
               <a href="{{ route('mahasiswas.create') }}" class="btn btn-info">Tambah Mahasiswa</a>
          @endauth
     </div>

     <table class="table table-striped">
          <thead>
               <tr>
                    <th>#</th>
                    <th>NIM</th>
                    <th>Nama Mahasiswa</th>
                    <th>Jurusan Mahasiswa</th>
                    @auth
                    <th>Action</th>
                    @endauth
               </tr>
          </thead>
          <tbody>
               @foreach ($mahasiswas as $mahasiswa)
                    <tr id="row-{{ $mahasiswa->id }}">
                         <th>{{ $mahasiswas->firstItem() + $loop->iteration - 1 }}</th>
                         <td>{{ $mahasiswa->nim }}</td>
                         <td>
                              <a href="{{ route('mahasiswas.show',['mahasiswa'=>$mahasiswa->id]) }}">{{$mahasiswa->nama}}</a>
                         </td>
                         <td>{{ $mahasiswa->jurusan->nama }}</td>
                         @auth
                         <td>
                              <a href="{{ route('mahasiswas.edit',['mahasiswa' => $mahasiswa->id]) }}" class="btn btn-secondary" title="Edit Mahasiswa">Edit</a>
                              <form action="{{ route('mahasiswas.destroy',['mahasiswa' => $mahasiswa->id]) }}" method="POST" class="d-inline">
                                   @csrf @method('DELETE')
                                   <button type="submit" class="btn btn-danger shadow-none btn-hapus" title="Hapus Mahasiswa" data-name="{{ $mahasiswa->nama }}">Hapus</button>
                              </form>
                         </td>
                         @endauth
                    </tr>
               @endforeach
          </tbody>
     </table>
     <div class="row">
          <div class="mx-auto mt-3"> 
               {{ $mahasiswas->fragment('judul')->links() }}
          </div>
     </div>
@endsection

resources/views/mahasiswa/show.blade.php
{{-- @php
     dump($matakuliahs->toArray())
@endphp --}}
@extends('layouts.app')
@section('content')
     <div class="pt-3 d-flex align-items-center">
          <h1 class="h2 me-4">Biodata Mahasiswa</h1>
          @auth
               <a href="{{ route('mahasiswas.edit',['mahasiswa' => $mahasiswa->id])}}"
               class="btn btn-secondary me-1" title="Edit Mahasiswa">Edit</a>
               <form action="{{ route('mahasiswas.destroy',
               ['mahasiswa' => $mahasiswa->id]) }}" method="POST" class="d-inline">
               @csrf @method('DELETE')
               <button type="submit" class="btn btn-danger shadow-none btn-hapus"
               title="Hapus Mahasiswa" data-name="{{$mahasiswa->nama}}" data-table="mahasiswa">
               Hapus</button>
               </form>
          @endauth
     </div>
     <hr>
     <ul>
          <li>Nama : <strong>{{ $mahasiswa->nama }}</strong></li>
          <li>NIM : <strong>{{ $mahasiswa->nim }}</strong></li>
          <li>Jurusan : <strong>{{ $mahasiswa->jurusan->nama }}</strong></li>
          <li>Total Matakuliah :
               <strong>{{ count($matakuliahs) }}</strong>
               ({{ $matakuliahs->sum('jumlah_sks') }} SKS)
          </li>
     </ul>
     <p>Mengambil Matakuliah : </p>
     <ol>
          @foreach ($matakuliahs as $matakuliah)
               <li>
                    {{ $matakuliah->nama }}
                    <small>
                         (<a href="{{ route('matakuliahs.show',['matakuliah' => $matakuliah->id]) }}">{{ $matakuliah->kode }}</a> {{ $matakuliah->jumlah_sks }} SKS)
                    </small>
               </li>
          @endforeach
     </ol>
     @auth
          <a href="{{ route('ambil-matakuliah',['mahasiswa' => $mahasiswa->id]) }}" class="btn btn-info" title="Daftarkan Mata Kuliah">Ambil Mata Kuliah</a>
     @endauth
@endsection